# Generated by Django 2.1.3 on 2018-11-26 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名前')),
                ('employee_number',models.IntegerField(max_length=128, verbose_name="社員番号")),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)], verbose_name='年齢')),
                ('section',models.CharField(max_length=200,choices=[(1, '管理本部'),(2, '財務部'),(3, '法務部'),(4, '人事部'),(5, '営業一部'),(6, '営業二部'),(7, 'IT一部'),(8, 'IT二部'),(9, '広報部')],default=4, verbose_name="部署")),
                ('rank',models.CharField(max_length=200,choices=[(1, '代表取締役社長'),(2, '常務取締役'),(3, '専務取締役'),(4, '本部長'),(5, '部長'),(6, '次長'),(7, '課長'),(8, '課長代理'),(9, '係長'),(10, '社員')],default=10, verbose_name='役職')),
                ('phone',models.IntegerField(max_length=20, verbose_name='電話番号')),
                ('email_add',models.CharField(max_length=100, verbose_name='メールアドレス')),
                ('postcode',models.CharField(max_length='20',verbose_name='郵便番号')),
                ('address',models.CharField(max_length=200, verbose_name='住所')),
                ('station1',models.CharField(max_length=20, verbose_name='最寄駅１')),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
        ),
    ]
